################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
OBJS := 
C++_DEPS := 
C_DEPS := 
CC_DEPS := 
CPP_DEPS := 
EXECUTABLES := 
CXX_DEPS := 
C_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
tests/reasoning/pln/unused \
tests/reasoning \
tests/persist/xml \
tests/embodiment/Control/Procedure/BuiltIn \
tests/embodiment/Control/PerceptionActionInterface \
opencog/web \
opencog/web/json_spirit \
opencog/util \
opencog/ubigraph \
opencog/spatial/math \
opencog/spatial \
opencog/shell \
opencog/server \
opencog/reasoning/pln/utils \
opencog/reasoning/pln/unused/utils \
opencog/reasoning/pln/unused \
opencog/reasoning/pln/rules/unify \
opencog/reasoning/pln/rules/simsubst \
opencog/reasoning/pln/rules/or \
opencog/reasoning/pln/rules/not \
opencog/reasoning/pln/rules/inference \
opencog/reasoning/pln/rules/implication \
opencog/reasoning/pln/rules/convert \
opencog/reasoning/pln/rules/auxiliary \
opencog/reasoning/pln/rules/and \
opencog/reasoning/pln/rules \
opencog/reasoning/pln/formulas \
opencog/reasoning/pln \
opencog/query \
opencog/python/util \
opencog/python/server \
opencog/python \
opencog/python/examples/hopfield \
opencog/python/examples/hello \
opencog/python/examples/custom_string \
opencog/python/dynamics \
opencog/python/dynamics/attention \
opencog/python/atomspace \
opencog/persist/xml \
opencog/persist/sql \
opencog/persist/memcache \
opencog/persist/hypertable \
opencog/persist/file \
opencog/nlp/wsd \
opencog/nlp/wordnet-import \
opencog/nlp/types \
opencog/nlp/question \
opencog/nlp/chatbot \
opencog/learning/moses/moses \
opencog/learning/moses/main \
opencog/learning/moses/eda \
opencog/learning/hillclimbing/main \
opencog/learning/hillclimbing \
opencog/guile \
opencog/embodiment/WorldWrapper \
opencog/embodiment/RuleValidation/VirtualWorldData \
opencog/embodiment/RuleValidation/Processor \
opencog/embodiment/PetComboVocabulary \
opencog/embodiment/Learning/main \
opencog/embodiment/Learning/behavior \
opencog/embodiment/Learning/RewritingRules \
opencog/embodiment/Learning/PetaverseMOSES \
opencog/embodiment/Learning/PetaverseHC \
opencog/embodiment/Learning/NoSpaceLife \
opencog/embodiment/Learning/LearningServerMessages \
opencog/embodiment/Learning/LearningServer \
opencog/embodiment/Learning/FitnessEstimator \
opencog/embodiment/Learning/Filter \
opencog/embodiment/Control/Procedure \
opencog/embodiment/Control/Procedure/BuiltIn \
opencog/embodiment/Control/PredicateUpdaters \
opencog/embodiment/Control/PerceptionActionInterface \
opencog/embodiment/Control/OperationalPetController \
opencog/embodiment/Control/MessagingSystem \
opencog/embodiment/Control \
opencog/embodiment/AutomatedSystemTest \
opencog/embodiment/AtomSpaceExtensions \
opencog/dynamics/attention \
opencog/dotty \
opencog/comboreduct/reduct \
opencog/comboreduct/main \
opencog/comboreduct/crutil \
opencog/comboreduct/combo \
opencog/comboreduct/ant_combo_vocabulary \
opencog/atomspace \
opencog/adaptors/tulip \
examples/server \
examples/modules \
examples/hopfield \
examples/atomtypes \
CMakeFiles/CompilerIdCXX \
CMakeFiles/CompilerIdC \

