# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bruce/code/AI/opencog

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bruce/code/AI/opencog/bin

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/bruce/code/AI/opencog/bin/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bruce/code/AI/opencog/bin/CMakeFiles /home/bruce/code/AI/opencog/bin/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bruce/code/AI/opencog/bin/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cscope

# Build rule for target.
cscope: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cscope
.PHONY : cscope

# fast build rule for target.
cscope/fast:
	$(MAKE) -f CMakeFiles/cscope.dir/build.make CMakeFiles/cscope.dir/build
.PHONY : cscope/fast

#=============================================================================
# Target rules for targets named doxygen

# Build rule for target.
doxygen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doxygen
.PHONY : doxygen

# fast build rule for target.
doxygen/fast:
	$(MAKE) -f CMakeFiles/doxygen.dir/build.make CMakeFiles/doxygen.dir/build
.PHONY : doxygen/fast

#=============================================================================
# Target rules for targets named examples

# Build rule for target.
examples: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 examples
.PHONY : examples

# fast build rule for target.
examples/fast:
	$(MAKE) -f CMakeFiles/examples.dir/build.make CMakeFiles/examples.dir/build
.PHONY : examples/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named util

# Build rule for target.
util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 util
.PHONY : util

# fast build rule for target.
util/fast:
	$(MAKE) -f opencog/util/CMakeFiles/util.dir/build.make opencog/util/CMakeFiles/util.dir/build
.PHONY : util/fast

#=============================================================================
# Target rules for targets named atomspace

# Build rule for target.
atomspace: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 atomspace
.PHONY : atomspace

# fast build rule for target.
atomspace/fast:
	$(MAKE) -f opencog/atomspace/CMakeFiles/atomspace.dir/build.make opencog/atomspace/CMakeFiles/atomspace.dir/build
.PHONY : atomspace/fast

#=============================================================================
# Target rules for targets named opencog_atom_types

# Build rule for target.
opencog_atom_types: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opencog_atom_types
.PHONY : opencog_atom_types

# fast build rule for target.
opencog_atom_types/fast:
	$(MAKE) -f opencog/atomspace/CMakeFiles/opencog_atom_types.dir/build.make opencog/atomspace/CMakeFiles/opencog_atom_types.dir/build
.PHONY : opencog_atom_types/fast

#=============================================================================
# Target rules for targets named attention

# Build rule for target.
attention: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 attention
.PHONY : attention

# fast build rule for target.
attention/fast:
	$(MAKE) -f opencog/dynamics/attention/CMakeFiles/attention.dir/build.make opencog/dynamics/attention/CMakeFiles/attention.dir/build
.PHONY : attention/fast

#=============================================================================
# Target rules for targets named attention_atom_types

# Build rule for target.
attention_atom_types: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 attention_atom_types
.PHONY : attention_atom_types

# fast build rule for target.
attention_atom_types/fast:
	$(MAKE) -f opencog/dynamics/attention/CMakeFiles/attention_atom_types.dir/build.make opencog/dynamics/attention/CMakeFiles/attention_atom_types.dir/build
.PHONY : attention_atom_types/fast

#=============================================================================
# Target rules for targets named builtinreqs

# Build rule for target.
builtinreqs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 builtinreqs
.PHONY : builtinreqs

# fast build rule for target.
builtinreqs/fast:
	$(MAKE) -f opencog/server/CMakeFiles/builtinreqs.dir/build.make opencog/server/CMakeFiles/builtinreqs.dir/build
.PHONY : builtinreqs/fast

#=============================================================================
# Target rules for targets named cogserver

# Build rule for target.
cogserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cogserver
.PHONY : cogserver

# fast build rule for target.
cogserver/fast:
	$(MAKE) -f opencog/server/CMakeFiles/cogserver.dir/build.make opencog/server/CMakeFiles/cogserver.dir/build
.PHONY : cogserver/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f opencog/server/CMakeFiles/server.dir/build.make opencog/server/CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named PrimitiveExample

# Build rule for target.
PrimitiveExample: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PrimitiveExample
.PHONY : PrimitiveExample

# fast build rule for target.
PrimitiveExample/fast:
	$(MAKE) -f opencog/guile/CMakeFiles/PrimitiveExample.dir/build.make opencog/guile/CMakeFiles/PrimitiveExample.dir/build
.PHONY : PrimitiveExample/fast

#=============================================================================
# Target rules for targets named smob

# Build rule for target.
smob: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 smob
.PHONY : smob

# fast build rule for target.
smob/fast:
	$(MAKE) -f opencog/guile/CMakeFiles/smob.dir/build.make opencog/guile/CMakeFiles/smob.dir/build
.PHONY : smob/fast

#=============================================================================
# Target rules for targets named scheme-shell

# Build rule for target.
scheme-shell: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scheme-shell
.PHONY : scheme-shell

# fast build rule for target.
scheme-shell/fast:
	$(MAKE) -f opencog/shell/CMakeFiles/scheme-shell.dir/build.make opencog/shell/CMakeFiles/scheme-shell.dir/build
.PHONY : scheme-shell/fast

#=============================================================================
# Target rules for targets named opencog_py

# Build rule for target.
opencog_py: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opencog_py
.PHONY : opencog_py

# fast build rule for target.
opencog_py/fast:
	$(MAKE) -f opencog/python/CMakeFiles/opencog_py.dir/build.make opencog/python/CMakeFiles/opencog_py.dir/build
.PHONY : opencog_py/fast

#=============================================================================
# Target rules for targets named atomspace_py

# Build rule for target.
atomspace_py: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 atomspace_py
.PHONY : atomspace_py

# fast build rule for target.
atomspace_py/fast:
	$(MAKE) -f opencog/python/atomspace/CMakeFiles/atomspace_py.dir/build.make opencog/python/atomspace/CMakeFiles/atomspace_py.dir/build
.PHONY : atomspace_py/fast

#=============================================================================
# Target rules for targets named server_py

# Build rule for target.
server_py: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server_py
.PHONY : server_py

# fast build rule for target.
server_py/fast:
	$(MAKE) -f opencog/python/server/CMakeFiles/server_py.dir/build.make opencog/python/server/CMakeFiles/server_py.dir/build
.PHONY : server_py/fast

#=============================================================================
# Target rules for targets named dynamics_py

# Build rule for target.
dynamics_py: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dynamics_py
.PHONY : dynamics_py

# fast build rule for target.
dynamics_py/fast:
	$(MAKE) -f opencog/python/dynamics/CMakeFiles/dynamics_py.dir/build.make opencog/python/dynamics/CMakeFiles/dynamics_py.dir/build
.PHONY : dynamics_py/fast

#=============================================================================
# Target rules for targets named attention_py

# Build rule for target.
attention_py: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 attention_py
.PHONY : attention_py

# fast build rule for target.
attention_py/fast:
	$(MAKE) -f opencog/python/dynamics/attention/CMakeFiles/attention_py.dir/build.make opencog/python/dynamics/attention/CMakeFiles/attention_py.dir/build
.PHONY : attention_py/fast

#=============================================================================
# Target rules for targets named util_py

# Build rule for target.
util_py: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 util_py
.PHONY : util_py

# fast build rule for target.
util_py/fast:
	$(MAKE) -f opencog/python/util/CMakeFiles/util_py.dir/build.make opencog/python/util/CMakeFiles/util_py.dir/build
.PHONY : util_py/fast

#=============================================================================
# Target rules for targets named custom_string_py

# Build rule for target.
custom_string_py: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 custom_string_py
.PHONY : custom_string_py

# fast build rule for target.
custom_string_py/fast:
	$(MAKE) -f opencog/python/examples/custom_string/CMakeFiles/custom_string_py.dir/build.make opencog/python/examples/custom_string/CMakeFiles/custom_string_py.dir/build
.PHONY : custom_string_py/fast

#=============================================================================
# Target rules for targets named hello_py

# Build rule for target.
hello_py: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hello_py
.PHONY : hello_py

# fast build rule for target.
hello_py/fast:
	$(MAKE) -f opencog/python/examples/hello/CMakeFiles/hello_py.dir/build.make opencog/python/examples/hello/CMakeFiles/hello_py.dir/build
.PHONY : hello_py/fast

#=============================================================================
# Target rules for targets named savable

# Build rule for target.
savable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 savable
.PHONY : savable

# fast build rule for target.
savable/fast:
	$(MAKE) -f opencog/persist/file/CMakeFiles/savable.dir/build.make opencog/persist/file/CMakeFiles/savable.dir/build
.PHONY : savable/fast

#=============================================================================
# Target rules for targets named persist

# Build rule for target.
persist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 persist
.PHONY : persist

# fast build rule for target.
persist/fast:
	$(MAKE) -f opencog/persist/sql/CMakeFiles/persist.dir/build.make opencog/persist/sql/CMakeFiles/persist.dir/build
.PHONY : persist/fast

#=============================================================================
# Target rules for targets named sniff

# Build rule for target.
sniff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sniff
.PHONY : sniff

# fast build rule for target.
sniff/fast:
	$(MAKE) -f opencog/persist/sql/CMakeFiles/sniff.dir/build.make opencog/persist/sql/CMakeFiles/sniff.dir/build
.PHONY : sniff/fast

#=============================================================================
# Target rules for targets named xml

# Build rule for target.
xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xml
.PHONY : xml

# fast build rule for target.
xml/fast:
	$(MAKE) -f opencog/persist/xml/CMakeFiles/xml.dir/build.make opencog/persist/xml/CMakeFiles/xml.dir/build
.PHONY : xml/fast

#=============================================================================
# Target rules for targets named adaptor-tulip

# Build rule for target.
adaptor-tulip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 adaptor-tulip
.PHONY : adaptor-tulip

# fast build rule for target.
adaptor-tulip/fast:
	$(MAKE) -f opencog/adaptors/tulip/CMakeFiles/adaptor-tulip.dir/build.make opencog/adaptors/tulip/CMakeFiles/adaptor-tulip.dir/build
.PHONY : adaptor-tulip/fast

#=============================================================================
# Target rules for targets named query

# Build rule for target.
query: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 query
.PHONY : query

# fast build rule for target.
query/fast:
	$(MAKE) -f opencog/query/CMakeFiles/query.dir/build.make opencog/query/CMakeFiles/query.dir/build
.PHONY : query/fast

#=============================================================================
# Target rules for targets named cogita

# Build rule for target.
cogita: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cogita
.PHONY : cogita

# fast build rule for target.
cogita/fast:
	$(MAKE) -f opencog/nlp/chatbot/CMakeFiles/cogita.dir/build.make opencog/nlp/chatbot/CMakeFiles/cogita.dir/build
.PHONY : cogita/fast

#=============================================================================
# Target rules for targets named nlp-types

# Build rule for target.
nlp-types: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nlp-types
.PHONY : nlp-types

# fast build rule for target.
nlp-types/fast:
	$(MAKE) -f opencog/nlp/types/CMakeFiles/nlp-types.dir/build.make opencog/nlp/types/CMakeFiles/nlp-types.dir/build
.PHONY : nlp-types/fast

#=============================================================================
# Target rules for targets named nlp_atom_types

# Build rule for target.
nlp_atom_types: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nlp_atom_types
.PHONY : nlp_atom_types

# fast build rule for target.
nlp_atom_types/fast:
	$(MAKE) -f opencog/nlp/types/CMakeFiles/nlp_atom_types.dir/build.make opencog/nlp/types/CMakeFiles/nlp_atom_types.dir/build
.PHONY : nlp_atom_types/fast

#=============================================================================
# Target rules for targets named wsd

# Build rule for target.
wsd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wsd
.PHONY : wsd

# fast build rule for target.
wsd/fast:
	$(MAKE) -f opencog/nlp/wsd/CMakeFiles/wsd.dir/build.make opencog/nlp/wsd/CMakeFiles/wsd.dir/build
.PHONY : wsd/fast

#=============================================================================
# Target rules for targets named pln

# Build rule for target.
pln: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pln
.PHONY : pln

# fast build rule for target.
pln/fast:
	$(MAKE) -f opencog/reasoning/pln/CMakeFiles/pln.dir/build.make opencog/reasoning/pln/CMakeFiles/pln.dir/build
.PHONY : pln/fast

#=============================================================================
# Target rules for targets named comboreduct

# Build rule for target.
comboreduct: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 comboreduct
.PHONY : comboreduct

# fast build rule for target.
comboreduct/fast:
	$(MAKE) -f opencog/comboreduct/CMakeFiles/comboreduct.dir/build.make opencog/comboreduct/CMakeFiles/comboreduct.dir/build
.PHONY : comboreduct/fast

#=============================================================================
# Target rules for targets named action-reductor

# Build rule for target.
action-reductor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 action-reductor
.PHONY : action-reductor

# fast build rule for target.
action-reductor/fast:
	$(MAKE) -f opencog/comboreduct/main/CMakeFiles/action-reductor.dir/build.make opencog/comboreduct/main/CMakeFiles/action-reductor.dir/build
.PHONY : action-reductor/fast

#=============================================================================
# Target rules for targets named contin-reductor

# Build rule for target.
contin-reductor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 contin-reductor
.PHONY : contin-reductor

# fast build rule for target.
contin-reductor/fast:
	$(MAKE) -f opencog/comboreduct/main/CMakeFiles/contin-reductor.dir/build.make opencog/comboreduct/main/CMakeFiles/contin-reductor.dir/build
.PHONY : contin-reductor/fast

#=============================================================================
# Target rules for targets named full-reductor

# Build rule for target.
full-reductor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 full-reductor
.PHONY : full-reductor

# fast build rule for target.
full-reductor/fast:
	$(MAKE) -f opencog/comboreduct/main/CMakeFiles/full-reductor.dir/build.make opencog/comboreduct/main/CMakeFiles/full-reductor.dir/build
.PHONY : full-reductor/fast

#=============================================================================
# Target rules for targets named interactive-reductor

# Build rule for target.
interactive-reductor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 interactive-reductor
.PHONY : interactive-reductor

# fast build rule for target.
interactive-reductor/fast:
	$(MAKE) -f opencog/comboreduct/main/CMakeFiles/interactive-reductor.dir/build.make opencog/comboreduct/main/CMakeFiles/interactive-reductor.dir/build
.PHONY : interactive-reductor/fast

#=============================================================================
# Target rules for targets named logical-reductor

# Build rule for target.
logical-reductor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 logical-reductor
.PHONY : logical-reductor

# fast build rule for target.
logical-reductor/fast:
	$(MAKE) -f opencog/comboreduct/main/CMakeFiles/logical-reductor.dir/build.make opencog/comboreduct/main/CMakeFiles/logical-reductor.dir/build
.PHONY : logical-reductor/fast

#=============================================================================
# Target rules for targets named mixed-reductor

# Build rule for target.
mixed-reductor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mixed-reductor
.PHONY : mixed-reductor

# fast build rule for target.
mixed-reductor/fast:
	$(MAKE) -f opencog/comboreduct/main/CMakeFiles/mixed-reductor.dir/build.make opencog/comboreduct/main/CMakeFiles/mixed-reductor.dir/build
.PHONY : mixed-reductor/fast

#=============================================================================
# Target rules for targets named perception-reductor

# Build rule for target.
perception-reductor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 perception-reductor
.PHONY : perception-reductor

# fast build rule for target.
perception-reductor/fast:
	$(MAKE) -f opencog/comboreduct/main/CMakeFiles/perception-reductor.dir/build.make opencog/comboreduct/main/CMakeFiles/perception-reductor.dir/build
.PHONY : perception-reductor/fast

#=============================================================================
# Target rules for targets named tree_gen

# Build rule for target.
tree_gen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tree_gen
.PHONY : tree_gen

# fast build rule for target.
tree_gen/fast:
	$(MAKE) -f opencog/comboreduct/main/CMakeFiles/tree_gen.dir/build.make opencog/comboreduct/main/CMakeFiles/tree_gen.dir/build
.PHONY : tree_gen/fast

#=============================================================================
# Target rules for targets named AStar

# Build rule for target.
AStar: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AStar
.PHONY : AStar

# fast build rule for target.
AStar/fast:
	$(MAKE) -f opencog/spatial/CMakeFiles/AStar.dir/build.make opencog/spatial/CMakeFiles/AStar.dir/build
.PHONY : AStar/fast

#=============================================================================
# Target rules for targets named HPASearch

# Build rule for target.
HPASearch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HPASearch
.PHONY : HPASearch

# fast build rule for target.
HPASearch/fast:
	$(MAKE) -f opencog/spatial/CMakeFiles/HPASearch.dir/build.make opencog/spatial/CMakeFiles/HPASearch.dir/build
.PHONY : HPASearch/fast

#=============================================================================
# Target rules for targets named MapTools

# Build rule for target.
MapTools: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MapTools
.PHONY : MapTools

# fast build rule for target.
MapTools/fast:
	$(MAKE) -f opencog/spatial/CMakeFiles/MapTools.dir/build.make opencog/spatial/CMakeFiles/MapTools.dir/build
.PHONY : MapTools/fast

#=============================================================================
# Target rules for targets named SpaceMap

# Build rule for target.
SpaceMap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SpaceMap
.PHONY : SpaceMap

# fast build rule for target.
SpaceMap/fast:
	$(MAKE) -f opencog/spatial/CMakeFiles/SpaceMap.dir/build.make opencog/spatial/CMakeFiles/SpaceMap.dir/build
.PHONY : SpaceMap/fast

#=============================================================================
# Target rules for targets named TangentBug

# Build rule for target.
TangentBug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TangentBug
.PHONY : TangentBug

# fast build rule for target.
TangentBug/fast:
	$(MAKE) -f opencog/spatial/CMakeFiles/TangentBug.dir/build.make opencog/spatial/CMakeFiles/TangentBug.dir/build
.PHONY : TangentBug/fast

#=============================================================================
# Target rules for targets named astartest

# Build rule for target.
astartest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 astartest
.PHONY : astartest

# fast build rule for target.
astartest/fast:
	$(MAKE) -f opencog/spatial/CMakeFiles/astartest.dir/build.make opencog/spatial/CMakeFiles/astartest.dir/build
.PHONY : astartest/fast

#=============================================================================
# Target rules for targets named tangentbug_test

# Build rule for target.
tangentbug_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tangentbug_test
.PHONY : tangentbug_test

# fast build rule for target.
tangentbug_test/fast:
	$(MAKE) -f opencog/spatial/CMakeFiles/tangentbug_test.dir/build.make opencog/spatial/CMakeFiles/tangentbug_test.dir/build
.PHONY : tangentbug_test/fast

#=============================================================================
# Target rules for targets named ocweb

# Build rule for target.
ocweb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ocweb
.PHONY : ocweb

# fast build rule for target.
ocweb/fast:
	$(MAKE) -f opencog/web/CMakeFiles/ocweb.dir/build.make opencog/web/CMakeFiles/ocweb.dir/build
.PHONY : ocweb/fast

#=============================================================================
# Target rules for targets named json_spirit

# Build rule for target.
json_spirit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 json_spirit
.PHONY : json_spirit

# fast build rule for target.
json_spirit/fast:
	$(MAKE) -f opencog/web/json_spirit/CMakeFiles/json_spirit.dir/build.make opencog/web/json_spirit/CMakeFiles/json_spirit.dir/build
.PHONY : json_spirit/fast

#=============================================================================
# Target rules for targets named moses

# Build rule for target.
moses: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 moses
.PHONY : moses

# fast build rule for target.
moses/fast:
	$(MAKE) -f opencog/learning/moses/CMakeFiles/moses.dir/build.make opencog/learning/moses/CMakeFiles/moses.dir/build
.PHONY : moses/fast

#=============================================================================
# Target rules for targets named build-representation

# Build rule for target.
build-representation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 build-representation
.PHONY : build-representation

# fast build rule for target.
build-representation/fast:
	$(MAKE) -f opencog/learning/moses/main/CMakeFiles/build-representation.dir/build.make opencog/learning/moses/main/CMakeFiles/build-representation.dir/build
.PHONY : build-representation/fast

#=============================================================================
# Target rules for targets named continmax

# Build rule for target.
continmax: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 continmax
.PHONY : continmax

# fast build rule for target.
continmax/fast:
	$(MAKE) -f opencog/learning/moses/main/CMakeFiles/continmax.dir/build.make opencog/learning/moses/main/CMakeFiles/continmax.dir/build
.PHONY : continmax/fast

#=============================================================================
# Target rules for targets named eval-truth-table

# Build rule for target.
eval-truth-table: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eval-truth-table
.PHONY : eval-truth-table

# fast build rule for target.
eval-truth-table/fast:
	$(MAKE) -f opencog/learning/moses/main/CMakeFiles/eval-truth-table.dir/build.make opencog/learning/moses/main/CMakeFiles/eval-truth-table.dir/build
.PHONY : eval-truth-table/fast

#=============================================================================
# Target rules for targets named gen-contin-table

# Build rule for target.
gen-contin-table: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gen-contin-table
.PHONY : gen-contin-table

# fast build rule for target.
gen-contin-table/fast:
	$(MAKE) -f opencog/learning/moses/main/CMakeFiles/gen-contin-table.dir/build.make opencog/learning/moses/main/CMakeFiles/gen-contin-table.dir/build
.PHONY : gen-contin-table/fast

#=============================================================================
# Target rules for targets named gen-mixed-table

# Build rule for target.
gen-mixed-table: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gen-mixed-table
.PHONY : gen-mixed-table

# fast build rule for target.
gen-mixed-table/fast:
	$(MAKE) -f opencog/learning/moses/main/CMakeFiles/gen-mixed-table.dir/build.make opencog/learning/moses/main/CMakeFiles/gen-mixed-table.dir/build
.PHONY : gen-mixed-table/fast

#=============================================================================
# Target rules for targets named gen-truth-table

# Build rule for target.
gen-truth-table: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gen-truth-table
.PHONY : gen-truth-table

# fast build rule for target.
gen-truth-table/fast:
	$(MAKE) -f opencog/learning/moses/main/CMakeFiles/gen-truth-table.dir/build.make opencog/learning/moses/main/CMakeFiles/gen-truth-table.dir/build
.PHONY : gen-truth-table/fast

#=============================================================================
# Target rules for targets named moses-ann-pole1

# Build rule for target.
moses-ann-pole1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 moses-ann-pole1
.PHONY : moses-ann-pole1

# fast build rule for target.
moses-ann-pole1/fast:
	$(MAKE) -f opencog/learning/moses/main/CMakeFiles/moses-ann-pole1.dir/build.make opencog/learning/moses/main/CMakeFiles/moses-ann-pole1.dir/build
.PHONY : moses-ann-pole1/fast

#=============================================================================
# Target rules for targets named moses-ann-pole2

# Build rule for target.
moses-ann-pole2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 moses-ann-pole2
.PHONY : moses-ann-pole2

# fast build rule for target.
moses-ann-pole2/fast:
	$(MAKE) -f opencog/learning/moses/main/CMakeFiles/moses-ann-pole2.dir/build.make opencog/learning/moses/main/CMakeFiles/moses-ann-pole2.dir/build
.PHONY : moses-ann-pole2/fast

#=============================================================================
# Target rules for targets named moses-ann-pole2-hillclimbing

# Build rule for target.
moses-ann-pole2-hillclimbing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 moses-ann-pole2-hillclimbing
.PHONY : moses-ann-pole2-hillclimbing

# fast build rule for target.
moses-ann-pole2-hillclimbing/fast:
	$(MAKE) -f opencog/learning/moses/main/CMakeFiles/moses-ann-pole2-hillclimbing.dir/build.make opencog/learning/moses/main/CMakeFiles/moses-ann-pole2-hillclimbing.dir/build
.PHONY : moses-ann-pole2-hillclimbing/fast

#=============================================================================
# Target rules for targets named moses-ann-pole2nv

# Build rule for target.
moses-ann-pole2nv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 moses-ann-pole2nv
.PHONY : moses-ann-pole2nv

# fast build rule for target.
moses-ann-pole2nv/fast:
	$(MAKE) -f opencog/learning/moses/main/CMakeFiles/moses-ann-pole2nv.dir/build.make opencog/learning/moses/main/CMakeFiles/moses-ann-pole2nv.dir/build
.PHONY : moses-ann-pole2nv/fast

#=============================================================================
# Target rules for targets named moses-ann-xor

# Build rule for target.
moses-ann-xor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 moses-ann-xor
.PHONY : moses-ann-xor

# fast build rule for target.
moses-ann-xor/fast:
	$(MAKE) -f opencog/learning/moses/main/CMakeFiles/moses-ann-xor.dir/build.make opencog/learning/moses/main/CMakeFiles/moses-ann-xor.dir/build
.PHONY : moses-ann-xor/fast

#=============================================================================
# Target rules for targets named moses-ant-hillclimbing

# Build rule for target.
moses-ant-hillclimbing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 moses-ant-hillclimbing
.PHONY : moses-ant-hillclimbing

# fast build rule for target.
moses-ant-hillclimbing/fast:
	$(MAKE) -f opencog/learning/moses/main/CMakeFiles/moses-ant-hillclimbing.dir/build.make opencog/learning/moses/main/CMakeFiles/moses-ant-hillclimbing.dir/build
.PHONY : moses-ant-hillclimbing/fast

#=============================================================================
# Target rules for targets named moses-exec

# Build rule for target.
moses-exec: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 moses-exec
.PHONY : moses-exec

# fast build rule for target.
moses-exec/fast:
	$(MAKE) -f opencog/learning/moses/main/CMakeFiles/moses-exec.dir/build.make opencog/learning/moses/main/CMakeFiles/moses-exec.dir/build
.PHONY : moses-exec/fast

#=============================================================================
# Target rules for targets named nmax

# Build rule for target.
nmax: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nmax
.PHONY : nmax

# fast build rule for target.
nmax/fast:
	$(MAKE) -f opencog/learning/moses/main/CMakeFiles/nmax.dir/build.make opencog/learning/moses/main/CMakeFiles/nmax.dir/build
.PHONY : nmax/fast

#=============================================================================
# Target rules for targets named onemax

# Build rule for target.
onemax: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 onemax
.PHONY : onemax

# fast build rule for target.
onemax/fast:
	$(MAKE) -f opencog/learning/moses/main/CMakeFiles/onemax.dir/build.make opencog/learning/moses/main/CMakeFiles/onemax.dir/build
.PHONY : onemax/fast

#=============================================================================
# Target rules for targets named ontomax

# Build rule for target.
ontomax: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ontomax
.PHONY : ontomax

# fast build rule for target.
ontomax/fast:
	$(MAKE) -f opencog/learning/moses/main/CMakeFiles/ontomax.dir/build.make opencog/learning/moses/main/CMakeFiles/ontomax.dir/build
.PHONY : ontomax/fast

#=============================================================================
# Target rules for targets named hillclimbing

# Build rule for target.
hillclimbing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hillclimbing
.PHONY : hillclimbing

# fast build rule for target.
hillclimbing/fast:
	$(MAKE) -f opencog/learning/hillclimbing/CMakeFiles/hillclimbing.dir/build.make opencog/learning/hillclimbing/CMakeFiles/hillclimbing.dir/build
.PHONY : hillclimbing/fast

#=============================================================================
# Target rules for targets named ant-hillclimbing

# Build rule for target.
ant-hillclimbing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ant-hillclimbing
.PHONY : ant-hillclimbing

# fast build rule for target.
ant-hillclimbing/fast:
	$(MAKE) -f opencog/learning/hillclimbing/main/CMakeFiles/ant-hillclimbing.dir/build.make opencog/learning/hillclimbing/main/CMakeFiles/ant-hillclimbing.dir/build
.PHONY : ant-hillclimbing/fast

#=============================================================================
# Target rules for targets named dotty

# Build rule for target.
dotty: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dotty
.PHONY : dotty

# fast build rule for target.
dotty/fast:
	$(MAKE) -f opencog/dotty/CMakeFiles/dotty.dir/build.make opencog/dotty/CMakeFiles/dotty.dir/build
.PHONY : dotty/fast

#=============================================================================
# Target rules for targets named ubigraph

# Build rule for target.
ubigraph: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ubigraph
.PHONY : ubigraph

# fast build rule for target.
ubigraph/fast:
	$(MAKE) -f opencog/ubigraph/CMakeFiles/ubigraph.dir/build.make opencog/ubigraph/CMakeFiles/ubigraph.dir/build
.PHONY : ubigraph/fast

#=============================================================================
# Target rules for targets named ConfigUTest

# Build rule for target.
ConfigUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ConfigUTest
.PHONY : ConfigUTest

# fast build rule for target.
ConfigUTest/fast:
	$(MAKE) -f tests/util/CMakeFiles/ConfigUTest.dir/build.make tests/util/CMakeFiles/ConfigUTest.dir/build
.PHONY : ConfigUTest/fast

#=============================================================================
# Target rules for targets named LoggerUTest

# Build rule for target.
LoggerUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LoggerUTest
.PHONY : LoggerUTest

# fast build rule for target.
LoggerUTest/fast:
	$(MAKE) -f tests/util/CMakeFiles/LoggerUTest.dir/build.make tests/util/CMakeFiles/LoggerUTest.dir/build
.PHONY : LoggerUTest/fast

#=============================================================================
# Target rules for targets named StringTokenizerUTest

# Build rule for target.
StringTokenizerUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 StringTokenizerUTest
.PHONY : StringTokenizerUTest

# fast build rule for target.
StringTokenizerUTest/fast:
	$(MAKE) -f tests/util/CMakeFiles/StringTokenizerUTest.dir/build.make tests/util/CMakeFiles/StringTokenizerUTest.dir/build
.PHONY : StringTokenizerUTest/fast

#=============================================================================
# Target rules for targets named iostreamContainerUTest

# Build rule for target.
iostreamContainerUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iostreamContainerUTest
.PHONY : iostreamContainerUTest

# fast build rule for target.
iostreamContainerUTest/fast:
	$(MAKE) -f tests/util/CMakeFiles/iostreamContainerUTest.dir/build.make tests/util/CMakeFiles/iostreamContainerUTest.dir/build
.PHONY : iostreamContainerUTest/fast

#=============================================================================
# Target rules for targets named lazy_selectorUTest

# Build rule for target.
lazy_selectorUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lazy_selectorUTest
.PHONY : lazy_selectorUTest

# fast build rule for target.
lazy_selectorUTest/fast:
	$(MAKE) -f tests/util/CMakeFiles/lazy_selectorUTest.dir/build.make tests/util/CMakeFiles/lazy_selectorUTest.dir/build
.PHONY : lazy_selectorUTest/fast

#=============================================================================
# Target rules for targets named numericUTest

# Build rule for target.
numericUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 numericUTest
.PHONY : numericUTest

# fast build rule for target.
numericUTest/fast:
	$(MAKE) -f tests/util/CMakeFiles/numericUTest.dir/build.make tests/util/CMakeFiles/numericUTest.dir/build
.PHONY : numericUTest/fast

#=============================================================================
# Target rules for targets named AtomSpaceUTest

# Build rule for target.
AtomSpaceUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AtomSpaceUTest
.PHONY : AtomSpaceUTest

# fast build rule for target.
AtomSpaceUTest/fast:
	$(MAKE) -f tests/atomspace/CMakeFiles/AtomSpaceUTest.dir/build.make tests/atomspace/CMakeFiles/AtomSpaceUTest.dir/build
.PHONY : AtomSpaceUTest/fast

#=============================================================================
# Target rules for targets named AtomTableUTest

# Build rule for target.
AtomTableUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AtomTableUTest
.PHONY : AtomTableUTest

# fast build rule for target.
AtomTableUTest/fast:
	$(MAKE) -f tests/atomspace/CMakeFiles/AtomTableUTest.dir/build.make tests/atomspace/CMakeFiles/AtomTableUTest.dir/build
.PHONY : AtomTableUTest/fast

#=============================================================================
# Target rules for targets named AtomUTest

# Build rule for target.
AtomUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AtomUTest
.PHONY : AtomUTest

# fast build rule for target.
AtomUTest/fast:
	$(MAKE) -f tests/atomspace/CMakeFiles/AtomUTest.dir/build.make tests/atomspace/CMakeFiles/AtomUTest.dir/build
.PHONY : AtomUTest/fast

#=============================================================================
# Target rules for targets named AttentionValueUTest

# Build rule for target.
AttentionValueUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AttentionValueUTest
.PHONY : AttentionValueUTest

# fast build rule for target.
AttentionValueUTest/fast:
	$(MAKE) -f tests/atomspace/CMakeFiles/AttentionValueUTest.dir/build.make tests/atomspace/CMakeFiles/AttentionValueUTest.dir/build
.PHONY : AttentionValueUTest/fast

#=============================================================================
# Target rules for targets named ClassServerUTest

# Build rule for target.
ClassServerUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ClassServerUTest
.PHONY : ClassServerUTest

# fast build rule for target.
ClassServerUTest/fast:
	$(MAKE) -f tests/atomspace/CMakeFiles/ClassServerUTest.dir/build.make tests/atomspace/CMakeFiles/ClassServerUTest.dir/build
.PHONY : ClassServerUTest/fast

#=============================================================================
# Target rules for targets named CompositeTruthValueUTest

# Build rule for target.
CompositeTruthValueUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CompositeTruthValueUTest
.PHONY : CompositeTruthValueUTest

# fast build rule for target.
CompositeTruthValueUTest/fast:
	$(MAKE) -f tests/atomspace/CMakeFiles/CompositeTruthValueUTest.dir/build.make tests/atomspace/CMakeFiles/CompositeTruthValueUTest.dir/build
.PHONY : CompositeTruthValueUTest/fast

#=============================================================================
# Target rules for targets named HandleEntryUTest

# Build rule for target.
HandleEntryUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HandleEntryUTest
.PHONY : HandleEntryUTest

# fast build rule for target.
HandleEntryUTest/fast:
	$(MAKE) -f tests/atomspace/CMakeFiles/HandleEntryUTest.dir/build.make tests/atomspace/CMakeFiles/HandleEntryUTest.dir/build
.PHONY : HandleEntryUTest/fast

#=============================================================================
# Target rules for targets named HandleMapUTest

# Build rule for target.
HandleMapUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HandleMapUTest
.PHONY : HandleMapUTest

# fast build rule for target.
HandleMapUTest/fast:
	$(MAKE) -f tests/atomspace/CMakeFiles/HandleMapUTest.dir/build.make tests/atomspace/CMakeFiles/HandleMapUTest.dir/build
.PHONY : HandleMapUTest/fast

#=============================================================================
# Target rules for targets named HandleSetUTest

# Build rule for target.
HandleSetUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HandleSetUTest
.PHONY : HandleSetUTest

# fast build rule for target.
HandleSetUTest/fast:
	$(MAKE) -f tests/atomspace/CMakeFiles/HandleSetUTest.dir/build.make tests/atomspace/CMakeFiles/HandleSetUTest.dir/build
.PHONY : HandleSetUTest/fast

#=============================================================================
# Target rules for targets named IndefiniteTruthValueUTest

# Build rule for target.
IndefiniteTruthValueUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IndefiniteTruthValueUTest
.PHONY : IndefiniteTruthValueUTest

# fast build rule for target.
IndefiniteTruthValueUTest/fast:
	$(MAKE) -f tests/atomspace/CMakeFiles/IndefiniteTruthValueUTest.dir/build.make tests/atomspace/CMakeFiles/IndefiniteTruthValueUTest.dir/build
.PHONY : IndefiniteTruthValueUTest/fast

#=============================================================================
# Target rules for targets named LinkUTest

# Build rule for target.
LinkUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LinkUTest
.PHONY : LinkUTest

# fast build rule for target.
LinkUTest/fast:
	$(MAKE) -f tests/atomspace/CMakeFiles/LinkUTest.dir/build.make tests/atomspace/CMakeFiles/LinkUTest.dir/build
.PHONY : LinkUTest/fast

#=============================================================================
# Target rules for targets named NodeUTest

# Build rule for target.
NodeUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NodeUTest
.PHONY : NodeUTest

# fast build rule for target.
NodeUTest/fast:
	$(MAKE) -f tests/atomspace/CMakeFiles/NodeUTest.dir/build.make tests/atomspace/CMakeFiles/NodeUTest.dir/build
.PHONY : NodeUTest/fast

#=============================================================================
# Target rules for targets named SimpleTruthValueUTest

# Build rule for target.
SimpleTruthValueUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SimpleTruthValueUTest
.PHONY : SimpleTruthValueUTest

# fast build rule for target.
SimpleTruthValueUTest/fast:
	$(MAKE) -f tests/atomspace/CMakeFiles/SimpleTruthValueUTest.dir/build.make tests/atomspace/CMakeFiles/SimpleTruthValueUTest.dir/build
.PHONY : SimpleTruthValueUTest/fast

#=============================================================================
# Target rules for targets named TemporalMapUTest

# Build rule for target.
TemporalMapUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TemporalMapUTest
.PHONY : TemporalMapUTest

# fast build rule for target.
TemporalMapUTest/fast:
	$(MAKE) -f tests/atomspace/CMakeFiles/TemporalMapUTest.dir/build.make tests/atomspace/CMakeFiles/TemporalMapUTest.dir/build
.PHONY : TemporalMapUTest/fast

#=============================================================================
# Target rules for targets named TemporalTableUTest

# Build rule for target.
TemporalTableUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TemporalTableUTest
.PHONY : TemporalTableUTest

# fast build rule for target.
TemporalTableUTest/fast:
	$(MAKE) -f tests/atomspace/CMakeFiles/TemporalTableUTest.dir/build.make tests/atomspace/CMakeFiles/TemporalTableUTest.dir/build
.PHONY : TemporalTableUTest/fast

#=============================================================================
# Target rules for targets named TemporalUTest

# Build rule for target.
TemporalUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TemporalUTest
.PHONY : TemporalUTest

# fast build rule for target.
TemporalUTest/fast:
	$(MAKE) -f tests/atomspace/CMakeFiles/TemporalUTest.dir/build.make tests/atomspace/CMakeFiles/TemporalUTest.dir/build
.PHONY : TemporalUTest/fast

#=============================================================================
# Target rules for targets named TimeServerUTest

# Build rule for target.
TimeServerUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TimeServerUTest
.PHONY : TimeServerUTest

# fast build rule for target.
TimeServerUTest/fast:
	$(MAKE) -f tests/atomspace/CMakeFiles/TimeServerUTest.dir/build.make tests/atomspace/CMakeFiles/TimeServerUTest.dir/build
.PHONY : TimeServerUTest/fast

#=============================================================================
# Target rules for targets named TruthValueUTest

# Build rule for target.
TruthValueUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TruthValueUTest
.PHONY : TruthValueUTest

# fast build rule for target.
TruthValueUTest/fast:
	$(MAKE) -f tests/atomspace/CMakeFiles/TruthValueUTest.dir/build.make tests/atomspace/CMakeFiles/TruthValueUTest.dir/build
.PHONY : TruthValueUTest/fast

#=============================================================================
# Target rules for targets named SavingLoadingUTest

# Build rule for target.
SavingLoadingUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SavingLoadingUTest
.PHONY : SavingLoadingUTest

# fast build rule for target.
SavingLoadingUTest/fast:
	$(MAKE) -f tests/persist/file/CMakeFiles/SavingLoadingUTest.dir/build.make tests/persist/file/CMakeFiles/SavingLoadingUTest.dir/build
.PHONY : SavingLoadingUTest/fast

#=============================================================================
# Target rules for targets named test_custom_atom_types

# Build rule for target.
test_custom_atom_types: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_custom_atom_types
.PHONY : test_custom_atom_types

# fast build rule for target.
test_custom_atom_types/fast:
	$(MAKE) -f tests/persist/file/CMakeFiles/test_custom_atom_types.dir/build.make tests/persist/file/CMakeFiles/test_custom_atom_types.dir/build
.PHONY : test_custom_atom_types/fast

#=============================================================================
# Target rules for targets named BasicSaveUTest

# Build rule for target.
BasicSaveUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BasicSaveUTest
.PHONY : BasicSaveUTest

# fast build rule for target.
BasicSaveUTest/fast:
	$(MAKE) -f tests/persist/sql/CMakeFiles/BasicSaveUTest.dir/build.make tests/persist/sql/CMakeFiles/BasicSaveUTest.dir/build
.PHONY : BasicSaveUTest/fast

#=============================================================================
# Target rules for targets named NMXmlExporterUTest

# Build rule for target.
NMXmlExporterUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NMXmlExporterUTest
.PHONY : NMXmlExporterUTest

# fast build rule for target.
NMXmlExporterUTest/fast:
	$(MAKE) -f tests/persist/xml/CMakeFiles/NMXmlExporterUTest.dir/build.make tests/persist/xml/CMakeFiles/NMXmlExporterUTest.dir/build
.PHONY : NMXmlExporterUTest/fast

#=============================================================================
# Target rules for targets named NMXmlParserUTest

# Build rule for target.
NMXmlParserUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NMXmlParserUTest
.PHONY : NMXmlParserUTest

# fast build rule for target.
NMXmlParserUTest/fast:
	$(MAKE) -f tests/persist/xml/CMakeFiles/NMXmlParserUTest.dir/build.make tests/persist/xml/CMakeFiles/NMXmlParserUTest.dir/build
.PHONY : NMXmlParserUTest/fast

#=============================================================================
# Target rules for targets named BasicSCMUTest

# Build rule for target.
BasicSCMUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BasicSCMUTest
.PHONY : BasicSCMUTest

# fast build rule for target.
BasicSCMUTest/fast:
	$(MAKE) -f tests/scm/CMakeFiles/BasicSCMUTest.dir/build.make tests/scm/CMakeFiles/BasicSCMUTest.dir/build
.PHONY : BasicSCMUTest/fast

#=============================================================================
# Target rules for targets named SCMPrimitiveUTest

# Build rule for target.
SCMPrimitiveUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SCMPrimitiveUTest
.PHONY : SCMPrimitiveUTest

# fast build rule for target.
SCMPrimitiveUTest/fast:
	$(MAKE) -f tests/scm/CMakeFiles/SCMPrimitiveUTest.dir/build.make tests/scm/CMakeFiles/SCMPrimitiveUTest.dir/build
.PHONY : SCMPrimitiveUTest/fast

#=============================================================================
# Target rules for targets named BigPatternUTest

# Build rule for target.
BigPatternUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BigPatternUTest
.PHONY : BigPatternUTest

# fast build rule for target.
BigPatternUTest/fast:
	$(MAKE) -f tests/query/CMakeFiles/BigPatternUTest.dir/build.make tests/query/CMakeFiles/BigPatternUTest.dir/build
.PHONY : BigPatternUTest/fast

#=============================================================================
# Target rules for targets named BiggerPatternUTest

# Build rule for target.
BiggerPatternUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BiggerPatternUTest
.PHONY : BiggerPatternUTest

# fast build rule for target.
BiggerPatternUTest/fast:
	$(MAKE) -f tests/query/CMakeFiles/BiggerPatternUTest.dir/build.make tests/query/CMakeFiles/BiggerPatternUTest.dir/build
.PHONY : BiggerPatternUTest/fast

#=============================================================================
# Target rules for targets named Boolean2NotUTest

# Build rule for target.
Boolean2NotUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Boolean2NotUTest
.PHONY : Boolean2NotUTest

# fast build rule for target.
Boolean2NotUTest/fast:
	$(MAKE) -f tests/query/CMakeFiles/Boolean2NotUTest.dir/build.make tests/query/CMakeFiles/Boolean2NotUTest.dir/build
.PHONY : Boolean2NotUTest/fast

#=============================================================================
# Target rules for targets named BooleanUTest

# Build rule for target.
BooleanUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BooleanUTest
.PHONY : BooleanUTest

# fast build rule for target.
BooleanUTest/fast:
	$(MAKE) -f tests/query/CMakeFiles/BooleanUTest.dir/build.make tests/query/CMakeFiles/BooleanUTest.dir/build
.PHONY : BooleanUTest/fast

#=============================================================================
# Target rules for targets named BuggyStackUTest

# Build rule for target.
BuggyStackUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BuggyStackUTest
.PHONY : BuggyStackUTest

# fast build rule for target.
BuggyStackUTest/fast:
	$(MAKE) -f tests/query/CMakeFiles/BuggyStackUTest.dir/build.make tests/query/CMakeFiles/BuggyStackUTest.dir/build
.PHONY : BuggyStackUTest/fast

#=============================================================================
# Target rules for targets named ExecutionUTest

# Build rule for target.
ExecutionUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExecutionUTest
.PHONY : ExecutionUTest

# fast build rule for target.
ExecutionUTest/fast:
	$(MAKE) -f tests/query/CMakeFiles/ExecutionUTest.dir/build.make tests/query/CMakeFiles/ExecutionUTest.dir/build
.PHONY : ExecutionUTest/fast

#=============================================================================
# Target rules for targets named ImplicationUTest

# Build rule for target.
ImplicationUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ImplicationUTest
.PHONY : ImplicationUTest

# fast build rule for target.
ImplicationUTest/fast:
	$(MAKE) -f tests/query/CMakeFiles/ImplicationUTest.dir/build.make tests/query/CMakeFiles/ImplicationUTest.dir/build
.PHONY : ImplicationUTest/fast

#=============================================================================
# Target rules for targets named LoopPatternUTest

# Build rule for target.
LoopPatternUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LoopPatternUTest
.PHONY : LoopPatternUTest

# fast build rule for target.
LoopPatternUTest/fast:
	$(MAKE) -f tests/query/CMakeFiles/LoopPatternUTest.dir/build.make tests/query/CMakeFiles/LoopPatternUTest.dir/build
.PHONY : LoopPatternUTest/fast

#=============================================================================
# Target rules for targets named PatternUTest

# Build rule for target.
PatternUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PatternUTest
.PHONY : PatternUTest

# fast build rule for target.
PatternUTest/fast:
	$(MAKE) -f tests/query/CMakeFiles/PatternUTest.dir/build.make tests/query/CMakeFiles/PatternUTest.dir/build
.PHONY : PatternUTest/fast

#=============================================================================
# Target rules for targets named StackUTest

# Build rule for target.
StackUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 StackUTest
.PHONY : StackUTest

# fast build rule for target.
StackUTest/fast:
	$(MAKE) -f tests/query/CMakeFiles/StackUTest.dir/build.make tests/query/CMakeFiles/StackUTest.dir/build
.PHONY : StackUTest/fast

#=============================================================================
# Target rules for targets named VarTypeNotUTest

# Build rule for target.
VarTypeNotUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 VarTypeNotUTest
.PHONY : VarTypeNotUTest

# fast build rule for target.
VarTypeNotUTest/fast:
	$(MAKE) -f tests/query/CMakeFiles/VarTypeNotUTest.dir/build.make tests/query/CMakeFiles/VarTypeNotUTest.dir/build
.PHONY : VarTypeNotUTest/fast

#=============================================================================
# Target rules for targets named AgentUTest

# Build rule for target.
AgentUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AgentUTest
.PHONY : AgentUTest

# fast build rule for target.
AgentUTest/fast:
	$(MAKE) -f tests/server/CMakeFiles/AgentUTest.dir/build.make tests/server/CMakeFiles/AgentUTest.dir/build
.PHONY : AgentUTest/fast

#=============================================================================
# Target rules for targets named CogServerUTest

# Build rule for target.
CogServerUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CogServerUTest
.PHONY : CogServerUTest

# fast build rule for target.
CogServerUTest/fast:
	$(MAKE) -f tests/server/CMakeFiles/CogServerUTest.dir/build.make tests/server/CMakeFiles/CogServerUTest.dir/build
.PHONY : CogServerUTest/fast

#=============================================================================
# Target rules for targets named ForgettingAgentUTest

# Build rule for target.
ForgettingAgentUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ForgettingAgentUTest
.PHONY : ForgettingAgentUTest

# fast build rule for target.
ForgettingAgentUTest/fast:
	$(MAKE) -f tests/dynamics/CMakeFiles/ForgettingAgentUTest.dir/build.make tests/dynamics/CMakeFiles/ForgettingAgentUTest.dir/build
.PHONY : ForgettingAgentUTest/fast

#=============================================================================
# Target rules for targets named HebbianUpdatingAgentUTest

# Build rule for target.
HebbianUpdatingAgentUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HebbianUpdatingAgentUTest
.PHONY : HebbianUpdatingAgentUTest

# fast build rule for target.
HebbianUpdatingAgentUTest/fast:
	$(MAKE) -f tests/dynamics/CMakeFiles/HebbianUpdatingAgentUTest.dir/build.make tests/dynamics/CMakeFiles/HebbianUpdatingAgentUTest.dir/build
.PHONY : HebbianUpdatingAgentUTest/fast

#=============================================================================
# Target rules for targets named ImportanceDiffusionAgentUTest

# Build rule for target.
ImportanceDiffusionAgentUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ImportanceDiffusionAgentUTest
.PHONY : ImportanceDiffusionAgentUTest

# fast build rule for target.
ImportanceDiffusionAgentUTest/fast:
	$(MAKE) -f tests/dynamics/CMakeFiles/ImportanceDiffusionAgentUTest.dir/build.make tests/dynamics/CMakeFiles/ImportanceDiffusionAgentUTest.dir/build
.PHONY : ImportanceDiffusionAgentUTest/fast

#=============================================================================
# Target rules for targets named ImportanceUpdatingAgentUTest

# Build rule for target.
ImportanceUpdatingAgentUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ImportanceUpdatingAgentUTest
.PHONY : ImportanceUpdatingAgentUTest

# fast build rule for target.
ImportanceUpdatingAgentUTest/fast:
	$(MAKE) -f tests/dynamics/CMakeFiles/ImportanceUpdatingAgentUTest.dir/build.make tests/dynamics/CMakeFiles/ImportanceUpdatingAgentUTest.dir/build
.PHONY : ImportanceUpdatingAgentUTest/fast

#=============================================================================
# Target rules for targets named STIDecayingAgentUTest

# Build rule for target.
STIDecayingAgentUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 STIDecayingAgentUTest
.PHONY : STIDecayingAgentUTest

# fast build rule for target.
STIDecayingAgentUTest/fast:
	$(MAKE) -f tests/dynamics/CMakeFiles/STIDecayingAgentUTest.dir/build.make tests/dynamics/CMakeFiles/STIDecayingAgentUTest.dir/build
.PHONY : STIDecayingAgentUTest/fast

#=============================================================================
# Target rules for targets named ASSOCUTest

# Build rule for target.
ASSOCUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ASSOCUTest
.PHONY : ASSOCUTest

# fast build rule for target.
ASSOCUTest/fast:
	$(MAKE) -f tests/reasoning/pln/CMakeFiles/ASSOCUTest.dir/build.make tests/reasoning/pln/CMakeFiles/ASSOCUTest.dir/build
.PHONY : ASSOCUTest/fast

#=============================================================================
# Target rules for targets named AtomSpaceWrapperUTest

# Build rule for target.
AtomSpaceWrapperUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AtomSpaceWrapperUTest
.PHONY : AtomSpaceWrapperUTest

# fast build rule for target.
AtomSpaceWrapperUTest/fast:
	$(MAKE) -f tests/reasoning/pln/CMakeFiles/AtomSpaceWrapperUTest.dir/build.make tests/reasoning/pln/CMakeFiles/AtomSpaceWrapperUTest.dir/build
.PHONY : AtomSpaceWrapperUTest/fast

#=============================================================================
# Target rules for targets named BITNodeUTest

# Build rule for target.
BITNodeUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BITNodeUTest
.PHONY : BITNodeUTest

# fast build rule for target.
BITNodeUTest/fast:
	$(MAKE) -f tests/reasoning/pln/CMakeFiles/BITNodeUTest.dir/build.make tests/reasoning/pln/CMakeFiles/BITNodeUTest.dir/build
.PHONY : BITNodeUTest/fast

#=============================================================================
# Target rules for targets named ConstitutedSetUTest

# Build rule for target.
ConstitutedSetUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ConstitutedSetUTest
.PHONY : ConstitutedSetUTest

# fast build rule for target.
ConstitutedSetUTest/fast:
	$(MAKE) -f tests/reasoning/pln/CMakeFiles/ConstitutedSetUTest.dir/build.make tests/reasoning/pln/CMakeFiles/ConstitutedSetUTest.dir/build
.PHONY : ConstitutedSetUTest/fast

#=============================================================================
# Target rules for targets named ForwardChainingUTest

# Build rule for target.
ForwardChainingUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ForwardChainingUTest
.PHONY : ForwardChainingUTest

# fast build rule for target.
ForwardChainingUTest/fast:
	$(MAKE) -f tests/reasoning/pln/CMakeFiles/ForwardChainingUTest.dir/build.make tests/reasoning/pln/CMakeFiles/ForwardChainingUTest.dir/build
.PHONY : ForwardChainingUTest/fast

#=============================================================================
# Target rules for targets named PLNUTest

# Build rule for target.
PLNUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PLNUTest
.PHONY : PLNUTest

# fast build rule for target.
PLNUTest/fast:
	$(MAKE) -f tests/reasoning/pln/CMakeFiles/PLNUTest.dir/build.make tests/reasoning/pln/CMakeFiles/PLNUTest.dir/build
.PHONY : PLNUTest/fast

#=============================================================================
# Target rules for targets named TableGatherUTest

# Build rule for target.
TableGatherUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TableGatherUTest
.PHONY : TableGatherUTest

# fast build rule for target.
TableGatherUTest/fast:
	$(MAKE) -f tests/reasoning/pln/CMakeFiles/TableGatherUTest.dir/build.make tests/reasoning/pln/CMakeFiles/TableGatherUTest.dir/build
.PHONY : TableGatherUTest/fast

#=============================================================================
# Target rules for targets named FormulaKitUTest

# Build rule for target.
FormulaKitUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FormulaKitUTest
.PHONY : FormulaKitUTest

# fast build rule for target.
FormulaKitUTest/fast:
	$(MAKE) -f tests/reasoning/pln/formulas/CMakeFiles/FormulaKitUTest.dir/build.make tests/reasoning/pln/formulas/CMakeFiles/FormulaKitUTest.dir/build
.PHONY : FormulaKitUTest/fast

#=============================================================================
# Target rules for targets named IndefinitePLNFormulaUTest

# Build rule for target.
IndefinitePLNFormulaUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IndefinitePLNFormulaUTest
.PHONY : IndefinitePLNFormulaUTest

# fast build rule for target.
IndefinitePLNFormulaUTest/fast:
	$(MAKE) -f tests/reasoning/pln/formulas/CMakeFiles/IndefinitePLNFormulaUTest.dir/build.make tests/reasoning/pln/formulas/CMakeFiles/IndefinitePLNFormulaUTest.dir/build
.PHONY : IndefinitePLNFormulaUTest/fast

#=============================================================================
# Target rules for targets named SubsetEvalFormulaUTest

# Build rule for target.
SubsetEvalFormulaUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SubsetEvalFormulaUTest
.PHONY : SubsetEvalFormulaUTest

# fast build rule for target.
SubsetEvalFormulaUTest/fast:
	$(MAKE) -f tests/reasoning/pln/formulas/CMakeFiles/SubsetEvalFormulaUTest.dir/build.make tests/reasoning/pln/formulas/CMakeFiles/SubsetEvalFormulaUTest.dir/build
.PHONY : SubsetEvalFormulaUTest/fast

#=============================================================================
# Target rules for targets named IntensionalInheritanceRuleUTest

# Build rule for target.
IntensionalInheritanceRuleUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IntensionalInheritanceRuleUTest
.PHONY : IntensionalInheritanceRuleUTest

# fast build rule for target.
IntensionalInheritanceRuleUTest/fast:
	$(MAKE) -f tests/reasoning/pln/rules/CMakeFiles/IntensionalInheritanceRuleUTest.dir/build.make tests/reasoning/pln/rules/CMakeFiles/IntensionalInheritanceRuleUTest.dir/build
.PHONY : IntensionalInheritanceRuleUTest/fast

#=============================================================================
# Target rules for targets named StrictImplicationBreakdownRuleUTest

# Build rule for target.
StrictImplicationBreakdownRuleUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 StrictImplicationBreakdownRuleUTest
.PHONY : StrictImplicationBreakdownRuleUTest

# fast build rule for target.
StrictImplicationBreakdownRuleUTest/fast:
	$(MAKE) -f tests/reasoning/pln/rules/CMakeFiles/StrictImplicationBreakdownRuleUTest.dir/build.make tests/reasoning/pln/rules/CMakeFiles/StrictImplicationBreakdownRuleUTest.dir/build
.PHONY : StrictImplicationBreakdownRuleUTest/fast

#=============================================================================
# Target rules for targets named SubsetEvalRuleUTest

# Build rule for target.
SubsetEvalRuleUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SubsetEvalRuleUTest
.PHONY : SubsetEvalRuleUTest

# fast build rule for target.
SubsetEvalRuleUTest/fast:
	$(MAKE) -f tests/reasoning/pln/rules/CMakeFiles/SubsetEvalRuleUTest.dir/build.make tests/reasoning/pln/rules/CMakeFiles/SubsetEvalRuleUTest.dir/build
.PHONY : SubsetEvalRuleUTest/fast

#=============================================================================
# Target rules for targets named annUTest

# Build rule for target.
annUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 annUTest
.PHONY : annUTest

# fast build rule for target.
annUTest/fast:
	$(MAKE) -f tests/comboreduct/combo/CMakeFiles/annUTest.dir/build.make tests/comboreduct/combo/CMakeFiles/annUTest.dir/build
.PHONY : annUTest/fast

#=============================================================================
# Target rules for targets named evalUTest

# Build rule for target.
evalUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 evalUTest
.PHONY : evalUTest

# fast build rule for target.
evalUTest/fast:
	$(MAKE) -f tests/comboreduct/combo/CMakeFiles/evalUTest.dir/build.make tests/comboreduct/combo/CMakeFiles/evalUTest.dir/build
.PHONY : evalUTest/fast

#=============================================================================
# Target rules for targets named messageUTest

# Build rule for target.
messageUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 messageUTest
.PHONY : messageUTest

# fast build rule for target.
messageUTest/fast:
	$(MAKE) -f tests/comboreduct/combo/CMakeFiles/messageUTest.dir/build.make tests/comboreduct/combo/CMakeFiles/messageUTest.dir/build
.PHONY : messageUTest/fast

#=============================================================================
# Target rules for targets named procedure_repositoryUTest

# Build rule for target.
procedure_repositoryUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 procedure_repositoryUTest
.PHONY : procedure_repositoryUTest

# fast build rule for target.
procedure_repositoryUTest/fast:
	$(MAKE) -f tests/comboreduct/combo/CMakeFiles/procedure_repositoryUTest.dir/build.make tests/comboreduct/combo/CMakeFiles/procedure_repositoryUTest.dir/build
.PHONY : procedure_repositoryUTest/fast

#=============================================================================
# Target rules for targets named type_treeUTest

# Build rule for target.
type_treeUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 type_treeUTest
.PHONY : type_treeUTest

# fast build rule for target.
type_treeUTest/fast:
	$(MAKE) -f tests/comboreduct/combo/CMakeFiles/type_treeUTest.dir/build.make tests/comboreduct/combo/CMakeFiles/type_treeUTest.dir/build
.PHONY : type_treeUTest/fast

#=============================================================================
# Target rules for targets named variable_unifierUTest

# Build rule for target.
variable_unifierUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 variable_unifierUTest
.PHONY : variable_unifierUTest

# fast build rule for target.
variable_unifierUTest/fast:
	$(MAKE) -f tests/comboreduct/combo/CMakeFiles/variable_unifierUTest.dir/build.make tests/comboreduct/combo/CMakeFiles/variable_unifierUTest.dir/build
.PHONY : variable_unifierUTest/fast

#=============================================================================
# Target rules for targets named vertexUTest

# Build rule for target.
vertexUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vertexUTest
.PHONY : vertexUTest

# fast build rule for target.
vertexUTest/fast:
	$(MAKE) -f tests/comboreduct/combo/CMakeFiles/vertexUTest.dir/build.make tests/comboreduct/combo/CMakeFiles/vertexUTest.dir/build
.PHONY : vertexUTest/fast

#=============================================================================
# Target rules for targets named ANNReductUTest

# Build rule for target.
ANNReductUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ANNReductUTest
.PHONY : ANNReductUTest

# fast build rule for target.
ANNReductUTest/fast:
	$(MAKE) -f tests/comboreduct/reduct/CMakeFiles/ANNReductUTest.dir/build.make tests/comboreduct/reduct/CMakeFiles/ANNReductUTest.dir/build
.PHONY : ANNReductUTest/fast

#=============================================================================
# Target rules for targets named BooleanReductUTest

# Build rule for target.
BooleanReductUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BooleanReductUTest
.PHONY : BooleanReductUTest

# fast build rule for target.
BooleanReductUTest/fast:
	$(MAKE) -f tests/comboreduct/reduct/CMakeFiles/BooleanReductUTest.dir/build.make tests/comboreduct/reduct/CMakeFiles/BooleanReductUTest.dir/build
.PHONY : BooleanReductUTest/fast

#=============================================================================
# Target rules for targets named ContinReductUTest

# Build rule for target.
ContinReductUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinReductUTest
.PHONY : ContinReductUTest

# fast build rule for target.
ContinReductUTest/fast:
	$(MAKE) -f tests/comboreduct/reduct/CMakeFiles/ContinReductUTest.dir/build.make tests/comboreduct/reduct/CMakeFiles/ContinReductUTest.dir/build
.PHONY : ContinReductUTest/fast

#=============================================================================
# Target rules for targets named FullReductUTest

# Build rule for target.
FullReductUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FullReductUTest
.PHONY : FullReductUTest

# fast build rule for target.
FullReductUTest/fast:
	$(MAKE) -f tests/comboreduct/reduct/CMakeFiles/FullReductUTest.dir/build.make tests/comboreduct/reduct/CMakeFiles/FullReductUTest.dir/build
.PHONY : FullReductUTest/fast

#=============================================================================
# Target rules for targets named MixedReductUTest

# Build rule for target.
MixedReductUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MixedReductUTest
.PHONY : MixedReductUTest

# fast build rule for target.
MixedReductUTest/fast:
	$(MAKE) -f tests/comboreduct/reduct/CMakeFiles/MixedReductUTest.dir/build.make tests/comboreduct/reduct/CMakeFiles/MixedReductUTest.dir/build
.PHONY : MixedReductUTest/fast

#=============================================================================
# Target rules for targets named HPASearchUTest

# Build rule for target.
HPASearchUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HPASearchUTest
.PHONY : HPASearchUTest

# fast build rule for target.
HPASearchUTest/fast:
	$(MAKE) -f tests/spatial/CMakeFiles/HPASearchUTest.dir/build.make tests/spatial/CMakeFiles/HPASearchUTest.dir/build
.PHONY : HPASearchUTest/fast

#=============================================================================
# Target rules for targets named LocalSpaceMap2DUTest

# Build rule for target.
LocalSpaceMap2DUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LocalSpaceMap2DUTest
.PHONY : LocalSpaceMap2DUTest

# fast build rule for target.
LocalSpaceMap2DUTest/fast:
	$(MAKE) -f tests/spatial/CMakeFiles/LocalSpaceMap2DUTest.dir/build.make tests/spatial/CMakeFiles/LocalSpaceMap2DUTest.dir/build
.PHONY : LocalSpaceMap2DUTest/fast

#=============================================================================
# Target rules for targets named MathUTest

# Build rule for target.
MathUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MathUTest
.PHONY : MathUTest

# fast build rule for target.
MathUTest/fast:
	$(MAKE) -f tests/spatial/CMakeFiles/MathUTest.dir/build.make tests/spatial/CMakeFiles/MathUTest.dir/build
.PHONY : MathUTest/fast

#=============================================================================
# Target rules for targets named VisibilityMapUTest

# Build rule for target.
VisibilityMapUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 VisibilityMapUTest
.PHONY : VisibilityMapUTest

# fast build rule for target.
VisibilityMapUTest/fast:
	$(MAKE) -f tests/spatial/CMakeFiles/VisibilityMapUTest.dir/build.make tests/spatial/CMakeFiles/VisibilityMapUTest.dir/build
.PHONY : VisibilityMapUTest/fast

#=============================================================================
# Target rules for targets named FieldSetUTest

# Build rule for target.
FieldSetUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FieldSetUTest
.PHONY : FieldSetUTest

# fast build rule for target.
FieldSetUTest/fast:
	$(MAKE) -f tests/learning/moses/CMakeFiles/FieldSetUTest.dir/build.make tests/learning/moses/CMakeFiles/FieldSetUTest.dir/build
.PHONY : FieldSetUTest/fast

#=============================================================================
# Target rules for targets named KnobTurningUTest

# Build rule for target.
KnobTurningUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KnobTurningUTest
.PHONY : KnobTurningUTest

# fast build rule for target.
KnobTurningUTest/fast:
	$(MAKE) -f tests/learning/moses/CMakeFiles/KnobTurningUTest.dir/build.make tests/learning/moses/CMakeFiles/KnobTurningUTest.dir/build
.PHONY : KnobTurningUTest/fast

#=============================================================================
# Target rules for targets named NeighborSamplingUTest

# Build rule for target.
NeighborSamplingUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NeighborSamplingUTest
.PHONY : NeighborSamplingUTest

# fast build rule for target.
NeighborSamplingUTest/fast:
	$(MAKE) -f tests/learning/moses/CMakeFiles/NeighborSamplingUTest.dir/build.make tests/learning/moses/CMakeFiles/NeighborSamplingUTest.dir/build
.PHONY : NeighborSamplingUTest/fast

#=============================================================================
# Target rules for targets named representationUTest

# Build rule for target.
representationUTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 representationUTest
.PHONY : representationUTest

# fast build rule for target.
representationUTest/fast:
	$(MAKE) -f tests/learning/moses/CMakeFiles/representationUTest.dir/build.make tests/learning/moses/CMakeFiles/representationUTest.dir/build
.PHONY : representationUTest/fast

#=============================================================================
# Target rules for targets named customatomtypes

# Build rule for target.
customatomtypes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 customatomtypes
.PHONY : customatomtypes

# fast build rule for target.
customatomtypes/fast:
	$(MAKE) -f examples/atomtypes/CMakeFiles/customatomtypes.dir/build.make examples/atomtypes/CMakeFiles/customatomtypes.dir/build
.PHONY : customatomtypes/fast

#=============================================================================
# Target rules for targets named examples_atom_types

# Build rule for target.
examples_atom_types: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 examples_atom_types
.PHONY : examples_atom_types

# fast build rule for target.
examples_atom_types/fast:
	$(MAKE) -f examples/atomtypes/CMakeFiles/examples_atom_types.dir/build.make examples/atomtypes/CMakeFiles/examples_atom_types.dir/build
.PHONY : examples_atom_types/fast

#=============================================================================
# Target rules for targets named hopfield

# Build rule for target.
hopfield: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hopfield
.PHONY : hopfield

# fast build rule for target.
hopfield/fast:
	$(MAKE) -f examples/hopfield/CMakeFiles/hopfield.dir/build.make examples/hopfield/CMakeFiles/hopfield.dir/build
.PHONY : hopfield/fast

#=============================================================================
# Target rules for targets named samplemodule

# Build rule for target.
samplemodule: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 samplemodule
.PHONY : samplemodule

# fast build rule for target.
samplemodule/fast:
	$(MAKE) -f examples/modules/CMakeFiles/samplemodule.dir/build.make examples/modules/CMakeFiles/samplemodule.dir/build
.PHONY : samplemodule/fast

#=============================================================================
# Target rules for targets named singleagentmodule

# Build rule for target.
singleagentmodule: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 singleagentmodule
.PHONY : singleagentmodule

# fast build rule for target.
singleagentmodule/fast:
	$(MAKE) -f examples/modules/CMakeFiles/singleagentmodule.dir/build.make examples/modules/CMakeFiles/singleagentmodule.dir/build
.PHONY : singleagentmodule/fast

#=============================================================================
# Target rules for targets named derivedserver

# Build rule for target.
derivedserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 derivedserver
.PHONY : derivedserver

# fast build rule for target.
derivedserver/fast:
	$(MAKE) -f examples/server/CMakeFiles/derivedserver.dir/build.make examples/server/CMakeFiles/derivedserver.dir/build
.PHONY : derivedserver/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... cscope"
	@echo "... doxygen"
	@echo "... edit_cache"
	@echo "... examples"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... tests"
	@echo "... util"
	@echo "... atomspace"
	@echo "... opencog_atom_types"
	@echo "... attention"
	@echo "... attention_atom_types"
	@echo "... builtinreqs"
	@echo "... cogserver"
	@echo "... server"
	@echo "... PrimitiveExample"
	@echo "... smob"
	@echo "... scheme-shell"
	@echo "... opencog_py"
	@echo "... atomspace_py"
	@echo "... server_py"
	@echo "... dynamics_py"
	@echo "... attention_py"
	@echo "... util_py"
	@echo "... custom_string_py"
	@echo "... hello_py"
	@echo "... savable"
	@echo "... persist"
	@echo "... sniff"
	@echo "... xml"
	@echo "... adaptor-tulip"
	@echo "... query"
	@echo "... cogita"
	@echo "... nlp-types"
	@echo "... nlp_atom_types"
	@echo "... wsd"
	@echo "... pln"
	@echo "... comboreduct"
	@echo "... action-reductor"
	@echo "... contin-reductor"
	@echo "... full-reductor"
	@echo "... interactive-reductor"
	@echo "... logical-reductor"
	@echo "... mixed-reductor"
	@echo "... perception-reductor"
	@echo "... tree_gen"
	@echo "... AStar"
	@echo "... HPASearch"
	@echo "... MapTools"
	@echo "... SpaceMap"
	@echo "... TangentBug"
	@echo "... astartest"
	@echo "... tangentbug_test"
	@echo "... ocweb"
	@echo "... json_spirit"
	@echo "... moses"
	@echo "... build-representation"
	@echo "... continmax"
	@echo "... eval-truth-table"
	@echo "... gen-contin-table"
	@echo "... gen-mixed-table"
	@echo "... gen-truth-table"
	@echo "... moses-ann-pole1"
	@echo "... moses-ann-pole2"
	@echo "... moses-ann-pole2-hillclimbing"
	@echo "... moses-ann-pole2nv"
	@echo "... moses-ann-xor"
	@echo "... moses-ant-hillclimbing"
	@echo "... moses-exec"
	@echo "... nmax"
	@echo "... onemax"
	@echo "... ontomax"
	@echo "... hillclimbing"
	@echo "... ant-hillclimbing"
	@echo "... dotty"
	@echo "... ubigraph"
	@echo "... ConfigUTest"
	@echo "... LoggerUTest"
	@echo "... StringTokenizerUTest"
	@echo "... iostreamContainerUTest"
	@echo "... lazy_selectorUTest"
	@echo "... numericUTest"
	@echo "... AtomSpaceUTest"
	@echo "... AtomTableUTest"
	@echo "... AtomUTest"
	@echo "... AttentionValueUTest"
	@echo "... ClassServerUTest"
	@echo "... CompositeTruthValueUTest"
	@echo "... HandleEntryUTest"
	@echo "... HandleMapUTest"
	@echo "... HandleSetUTest"
	@echo "... IndefiniteTruthValueUTest"
	@echo "... LinkUTest"
	@echo "... NodeUTest"
	@echo "... SimpleTruthValueUTest"
	@echo "... TemporalMapUTest"
	@echo "... TemporalTableUTest"
	@echo "... TemporalUTest"
	@echo "... TimeServerUTest"
	@echo "... TruthValueUTest"
	@echo "... SavingLoadingUTest"
	@echo "... test_custom_atom_types"
	@echo "... BasicSaveUTest"
	@echo "... NMXmlExporterUTest"
	@echo "... NMXmlParserUTest"
	@echo "... BasicSCMUTest"
	@echo "... SCMPrimitiveUTest"
	@echo "... BigPatternUTest"
	@echo "... BiggerPatternUTest"
	@echo "... Boolean2NotUTest"
	@echo "... BooleanUTest"
	@echo "... BuggyStackUTest"
	@echo "... ExecutionUTest"
	@echo "... ImplicationUTest"
	@echo "... LoopPatternUTest"
	@echo "... PatternUTest"
	@echo "... StackUTest"
	@echo "... VarTypeNotUTest"
	@echo "... AgentUTest"
	@echo "... CogServerUTest"
	@echo "... ForgettingAgentUTest"
	@echo "... HebbianUpdatingAgentUTest"
	@echo "... ImportanceDiffusionAgentUTest"
	@echo "... ImportanceUpdatingAgentUTest"
	@echo "... STIDecayingAgentUTest"
	@echo "... ASSOCUTest"
	@echo "... AtomSpaceWrapperUTest"
	@echo "... BITNodeUTest"
	@echo "... ConstitutedSetUTest"
	@echo "... ForwardChainingUTest"
	@echo "... PLNUTest"
	@echo "... TableGatherUTest"
	@echo "... FormulaKitUTest"
	@echo "... IndefinitePLNFormulaUTest"
	@echo "... SubsetEvalFormulaUTest"
	@echo "... IntensionalInheritanceRuleUTest"
	@echo "... StrictImplicationBreakdownRuleUTest"
	@echo "... SubsetEvalRuleUTest"
	@echo "... annUTest"
	@echo "... evalUTest"
	@echo "... messageUTest"
	@echo "... procedure_repositoryUTest"
	@echo "... type_treeUTest"
	@echo "... variable_unifierUTest"
	@echo "... vertexUTest"
	@echo "... ANNReductUTest"
	@echo "... BooleanReductUTest"
	@echo "... ContinReductUTest"
	@echo "... FullReductUTest"
	@echo "... MixedReductUTest"
	@echo "... HPASearchUTest"
	@echo "... LocalSpaceMap2DUTest"
	@echo "... MathUTest"
	@echo "... VisibilityMapUTest"
	@echo "... FieldSetUTest"
	@echo "... KnobTurningUTest"
	@echo "... NeighborSamplingUTest"
	@echo "... representationUTest"
	@echo "... customatomtypes"
	@echo "... examples_atom_types"
	@echo "... hopfield"
	@echo "... samplemodule"
	@echo "... singleagentmodule"
	@echo "... derivedserver"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

