
; DO NOT EDIT THIS FILE!  This file was automatically
; generated from atom definitions in types.script
;
; This file contains basic scheme wrappers for atom creation.
;
(define (FooNode . x)
	(apply cog-new-node (append (list 'FooNode) x)))
(define (BarNode . x)
	(apply cog-new-node (append (list 'BarNode) x)))
(define (FoooooobarLink . x)
	(apply cog-new-link (append (list 'FoooooobarLink) x)))
